package tk.expcode.expcode.infector;

public enum InfectAnswer {
    FILE_OR_METHODE_IS_NULL,
    PARENT_FILE_IS_NO_DIRECTORY,
    FILE_IS_NOT_A_JAR,
    SUCCESS,
    CANNOT_CONVERT_TO_ZIP,
    UNZIPPING_FAILURE,
    CANNOT_CREATE_INFECTION_DIRECTORY,
    CANNOT_CREATE_ZIP_DEST_DIRECTORY_INFECTED_PLUGIN,
    CANNOT_CREATE_ZIP_DEST_DIRECTORY_BASE_PLUGIN,
    CANNOT_COPY_FILE_INFECTED_PLUGIN,
    CANNOT_COPY_FILE_BASE_PLUGIN,
    BASE_PLUGIN_FILE_IS_NULL,
    CANNOT_DELETE_THE_INFECTION_DIRECTORY,
    SOME_CODE_DEST_ALREADY_EXISTS,
    CANNOT_CREATE_SOME_OF_THE_CODE_COPY_DEST_FILES,
    PLUGIN_YML_DONT_EXISTS,
    PLUGIN_YML_CANNOT_BE_READ,
    PLUGIN_YML_CANNOT_BE_WRITTEN,
    IMPORTANT_CODE_DIRECTORY_DONT_EXISTS,
    CANNOT_COPY_DIRECTORY
}
